version: "2"

services:

  api:
    build: https://github.com/SergeyDushkin/HelpDesk.Api.git
    links:
      - authorization-service
      - status-service
      - rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - backend

  authorization-service:
    build: https://github.com/SergeyDushkin/HelpDesk.Authorization.git
    networks:
      - backend

  status-service:
    build: https://github.com/SergeyDushkin/HelpDesk.StatusManagementSystem.git
    links:
      - authorization-service
      - rabbitmq
    depends_on:
      - rabbitmq
    ports:
      - '10010:10010'  
    networks:
      - backend

  signalr-service:
    build: https://github.com/SergeyDushkin/ServiceDesk.SignalR.git
    links:
      - authorization-service
      - rabbitmq
    depends_on:
      - rabbitmq
    ports:
      - '8080:15000' 
    networks:
      - frontend
      - backend

  web:
    build: https://github.com/SergeyDushkin/ServiceDesk.Web.git
    environment:
      VIRTUAL_HOST: "http://*/*"
    links:
      - authorization-service
      - signalr-service
      - api
    ports:
      - "80:80"
    networks:
      - frontend
      - backend

  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - backend

networks:
  frontend: 
    driver: bridge
  backend:
    driver: bridge