version: "2"

services:

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - rabbitmq
    command: rabbitmq:5672

  api:
    build: https://github.com/SergeyDushkin/HelpDesk.Api.git
    links:
      - authorization-service
      - status-service
      - rabbitmq
    ports:
      - '5000:5000'
    networks:
      - frontend

  authorization-service:
    build: https://github.com/SergeyDushkin/HelpDesk.Authorization.git
    ports:
      - '10001:5000'
    networks:
      - frontend

  status-service:
    build: https://github.com/SergeyDushkin/HelpDesk.StatusManagementSystem.git
    links:
      - authorization-service
      - rabbitmq
    ports:
      - '10010:10010'  
    networks:
      - backend

  signalr-service:
    build: https://github.com/SergeyDushkin/ServiceDesk.SignalR.git
    links:
      - authorization-service
      - rabbitmq
    ports:
      - '15000:15000'  

  web:
    build: https://github.com/SergeyDushkin/ServiceDesk.Web.git
    environment:
      VIRTUAL_HOST: "http://*/*"
    networks:
      - frontend

  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - backend

  lb:
    image: tutum/haproxy
    links:
      - web
    environment: 
      - DEFAULT_EXTRA_SETTINGS="http-response add-header X-Frame-Options SAMEORIGIN,http-response add-header X-Xss-Protection 1;mode=block"
    ports:
      - "80:80"
    networks:
      - backend
      - frontend

networks:
  frontend: 
    driver: bridge
  backend:
    driver: bridge